version: '3.3'
services:
  terraform:
   build:
     context: .
     dockerfile: terraform.Dockerfile
   environment:
     AWS_ACCESS_KEY: "AKIA2BKRFWRAGF4MVJFD"
     AWS_SECRET_ACCESS_KEY: "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"
     AWS_REGION: "us-east-1"
     AWS_DEFAULT_REGION: "us-east-1"
   volumes:
     - .:/app
  selenium:
   image: selenium/standalone-chrome-debug
   ports:
     - 4444:4444
     - 5901:5900
  website:
   build:
   name: website
    context: .
   ports:
    - 80:80
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - "./app:/app"
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb

